---

- name: Converge
  hosts: all
  become: "{{ molecule['converge']['become'] | default('yes') }}"
  vars:
    munge_key: tests/munge.key
  tasks:
    - name: Include role 'ansible-role-munge'
      ansible.builtin.include_role:
        name: ansible-role-munge
