---
- name: Converge
  hosts: all
  vars:
    munge_key: tests/munge.key
  tasks:

    - name: Update APT cache
      apt:
        update_cache: yes
        cache_valid_time: 1
      become: yes
      when: ansible_os_family == 'Debian'

    - name: "Include ansible-role-munge"
      include_role:
        name: "ansible-role-munge"
